language: node_js
node_js:
  - 8
  - 10
  - 11
  - 12

install:
  - npm ci
script:
  - npm t
after_success:
  - npm run docs
deploy:
  local_dir: ./docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
notifications:
  email:
    recipients:
      - brianloveswords@gmail.com
