language: node_js

notifications:
  email:
    recipients:
      - brianloveswords@gmail.com


install:
  - npm ci

jobs:
  include:
    - stage: "Test"
      name: "Node 8"
      node_js: "8"
      script: npm t

    - name: "Node 10"
      node_js: "10"
      script: npm t

    - name: "Node 11"
      node_js: "11"
      script: npm t
    
    - name: "Node 12"
      node_js: "12"
      script:
        - npm t

    - stage: "Deploy Docs to GH Pages"
      script: npm run docs
      deploy:
        local_dir: ./docs
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
